### PR TITLE
Added the required snippets in next-javascript.json file

### LINKED ISSUE #31: [FEATURE] Add imports and hooks to Typescript in React
### Description

The react imports and hooks don't work in typescript `tsx` files. So, we just need to add these imports in ts snippets JSON and add types if and where needed

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by itisaby**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

Check out the changes I made as requested in issue #41

### CODE REVIEW

**Review by avneesh0612 — CHANGES_REQUESTED** [review]
Hey, these need to be added in react ts and not next

**Comment by itisaby** [comment]
Alright I will fix it ASAP

**Comment by itisaby** [comment]
do checkout the changes :)

**Review by avneesh0612 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
